### ISSUE TITLE
every literal Double produces 'Not in scope: fromRational'

### ISSUE THREAD

**Issue by crooney** [crooney/cinder#3]
Every Double literal in the examples produces the above error, w/ nothing further. I see in the Fay changelog that fromRational was taken out last week, but I'm unclear on why it affects doubles. I'll dig in further if noone knows offhand, but I'm hoping it's something trivial that one of you guys knows about before I wade in. Cheers.

**Comment by bergmark** [comment]
I don't see this in the changelog, where does it say this?

Anyway, this is because of RebindableSyntax, from the GHC docs:
- An integer literal 368 means "fromInteger (368::Integer)", rather than "Prelude.fromInteger (368::Integer)".
- Fractional literals are handed in just the same way, except that the translation is fromRational (3.68::Rational).

We should export `fromRational` from `Prelude`, either it  was removed by accident or it was never present.

**Comment by bergmark** [comment]
Oh I randomly found some more info about this: faylang/fay-base#21

**Comment by bergmark** [comment]
To clarify the comments I made there, I think you can work around this for now by defining

```
fromRational :: Fractional a => ??? -> a
fromRational = ffi "%1"
```

This is just a phony function that won't be called (unless you call it explicitly in which case it won't do what you expect ;) ). Hacky hack, but you can try it out. Can't think right now it seems so i don't know what `???` should be, you can probably trial and error it to work.

**Comment by crooney** [comment]
Ok, thanks for the help; I will get on this shortly. The [changelog I mentioned](https://github.com/faylang/fay/blob/d90157b40998d599ca0c922266d2984e780910ea/CHANGELOG.md).

**Comment by bergmark** [comment]
The only mention of fromRational i see there is for the server-side type transcoding, which has no relation to this, am I missing something?

**Comment by crooney** [comment]
No, it's just that that was the only mention I saw; I should have looked in fay-base and not fay, but I'm stupid.

**Comment by bergmark** [comment]
Ok, no worries :)
